-- Generic multi-supplier quote store and safe optimizer settings.
-- Apply after the earlier supplier and fulfillment migrations.

alter table public.site_settings
  add column if not exists supplier_optimizer_enabled boolean not null default false,
  add column if not exists supplier_quote_ttl_minutes integer not null default 480,
  add column if not exists pricing_fee_percent numeric(7,4) not null default 0,
  add column if not exists pricing_fee_fixed_ils numeric(12,2) not null default 0,
  add column if not exists pricing_reserve_ils numeric(12,2) not null default 0;

alter table public.site_settings drop constraint if exists site_settings_supplier_quote_ttl_check;
alter table public.site_settings add constraint site_settings_supplier_quote_ttl_check
check (supplier_quote_ttl_minutes between 15 and 1440);
alter table public.site_settings drop constraint if exists site_settings_pricing_fee_percent_check;
alter table public.site_settings add constraint site_settings_pricing_fee_percent_check
check (pricing_fee_percent >= 0 and pricing_fee_percent < 100);
alter table public.site_settings drop constraint if exists site_settings_pricing_costs_nonnegative;
alter table public.site_settings add constraint site_settings_pricing_costs_nonnegative
check (pricing_fee_fixed_ils >= 0 and pricing_reserve_ils >= 0);

update public.site_settings
set minimum_profit_ils = coalesce(minimum_profit_ils, 20)
where id = 'primary';

create table if not exists public.supplier_offers (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  provider text not null,
  supplier_id text not null,
  supplier_url text,
  supplier_product_id text not null,
  supplier_sku_id text not null,
  supplier_sku_attr text,
  variant_label text,
  product_price_ils numeric(12,2),
  shipping_price_ils numeric(12,2),
  in_stock boolean,
  stock_quantity integer,
  shipping_available boolean,
  destination_country text not null default 'IL',
  estimated_delivery_days integer,
  equivalence_verified boolean not null default false,
  equivalence_verified_at timestamptz,
  fulfillment_supported boolean not null default false,
  provider_snapshot jsonb not null default '{}'::jsonb,
  last_sync_at timestamptz,
  shipping_last_checked_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint supplier_offers_provider_format check (provider ~ '^[a-z0-9_-]{2,40}$'),
  constraint supplier_offers_supplier_id_format check (supplier_id ~ '^[A-Za-z0-9:_-]{2,160}$'),
  constraint supplier_offers_destination_check check (destination_country ~ '^[A-Z]{2}$'),
  constraint supplier_offers_prices_nonnegative check (
    (product_price_ils is null or product_price_ils >= 0)
    and (shipping_price_ils is null or shipping_price_ils >= 0)
  ),
  constraint supplier_offers_stock_nonnegative check (stock_quantity is null or stock_quantity >= 0),
  constraint supplier_offers_delivery_nonnegative check (estimated_delivery_days is null or estimated_delivery_days >= 0),
  constraint supplier_offers_snapshot_object check (jsonb_typeof(provider_snapshot) = 'object')
);

create unique index if not exists supplier_offers_identity_uidx
on public.supplier_offers(product_id, provider, supplier_id, supplier_product_id, supplier_sku_id, coalesce(supplier_sku_attr, ''));
create index if not exists supplier_offers_optimizer_idx
on public.supplier_offers(product_id, destination_country, equivalence_verified, fulfillment_supported, in_stock, shipping_available);
create index if not exists supplier_offers_sync_idx
on public.supplier_offers(last_sync_at, shipping_last_checked_at);

alter table public.supplier_offers enable row level security;
revoke all privileges on table public.supplier_offers from public, anon, authenticated;
revoke all privileges on sequence public.supplier_offers_id_seq from public, anon, authenticated;
grant all privileges on table public.supplier_offers to service_role;
grant all privileges on sequence public.supplier_offers_id_seq to service_role;

create or replace function public.touch_supplier_offer_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke execute on function public.touch_supplier_offer_updated_at() from public, anon, authenticated;
drop trigger if exists supplier_offers_touch_updated_at on public.supplier_offers;
create trigger supplier_offers_touch_updated_at
before update on public.supplier_offers
for each row execute function public.touch_supplier_offer_updated_at();

alter table public.products
  add column if not exists selected_supplier_offer_id bigint references public.supplier_offers(id) on delete set null,
  add column if not exists supplier_landed_cost_ils numeric(12,2),
  add column if not exists supplier_selected_at timestamptz,
  add column if not exists supplier_selection_reason text;

alter table public.products drop constraint if exists products_supplier_landed_cost_nonnegative;
alter table public.products add constraint products_supplier_landed_cost_nonnegative
check (supplier_landed_cost_ils is null or supplier_landed_cost_ils >= 0);

-- Previous constraints only accepted AliExpress numeric IDs and URLs.
alter table public.products drop constraint if exists products_supplier_product_id_format;
alter table public.products add constraint products_supplier_product_id_format
check (supplier_product_id is null or supplier_product_id ~ '^[A-Za-z0-9:_-]{2,200}$');

alter table public.products drop constraint if exists products_supplier_url_format;
alter table public.products add constraint products_supplier_url_format
check (supplier_url is null or supplier_url ~* '^https://');

comment on table public.supplier_offers is
  'Server-only verified quotes for equivalent variants across suppliers. Unknown, stale, or non-fulfillable offers must never be auto-selected.';
comment on column public.site_settings.supplier_optimizer_enabled is
  'Master kill switch. Keep false until the migration, credentials, provider connectors, and dry run are verified.';

-- Paid fulfillment now supports both provider adapters already implemented by the app.
create or replace view public.product_fulfillment_readiness as
select
  p.id, p.name, p.active, p.fulfillment_ready, p.supplier,
  p.supplier_product_id, p.supplier_sku_id, p.variant_label,
  p.sku_verified_at, p.sku_verified_by, p.supplier_in_stock, p.supplier_stock,
  p.supplier_price_ils, p.supplier_shipping_available, p.supplier_shipping,
  p.last_sync_at, p.shipping_last_checked_at, p.supplier_sync_error, p.shipping_sync_error,
  nullif(trim(coalesce(p.supplier_product_id,'')),'') is not null as has_supplier_product_id,
  nullif(trim(coalesce(p.supplier_sku_id,'')),'') is not null as has_supplier_sku_id,
  (case when lower(coalesce(p.supplier,'')) = 'cj' then p.fulfillment_verified_at else p.sku_verified_at end) is not null as sku_verified,
  p.supplier_in_stock is not null as stock_known,
  p.supplier_shipping_available is not null as shipping_known,
  p.supplier_price_ils is not null as supplier_price_known,
  (
    p.active is true
    and p.fulfillment_ready is true
    and lower(coalesce(p.supplier,'')) in ('aliexpress','cj')
    and nullif(trim(coalesce(p.supplier_product_id,'')),'') is not null
    and nullif(trim(coalesce(p.supplier_sku_id,'')),'') is not null
    and (case when lower(coalesce(p.supplier,'')) = 'cj' then p.fulfillment_verified_at else p.sku_verified_at end) is not null
    and p.supplier_in_stock is true
    and p.supplier_shipping_available is true
    and p.supplier_price_ils is not null
    and p.last_sync_at >= now() - make_interval(mins => least(1440, greatest(15, coalesce(s.supplier_quote_ttl_minutes,480))))
    and p.shipping_last_checked_at >= now() - make_interval(mins => least(1440, greatest(15, coalesce(s.supplier_quote_ttl_minutes,480))))
    and p.supplier_sync_error is null and p.shipping_sync_error is null
    and p.selling_price - p.supplier_price_ils
      - ((p.selling_price + coalesce(p.supplier_shipping,0)) * coalesce(s.pricing_fee_percent,0) / 100)
      - coalesce(s.pricing_fee_fixed_ils,0) - coalesce(s.pricing_reserve_ils,0)
      >= greatest(20, coalesce(p.minimum_profit, s.minimum_profit_ils, 20))
    and (p.auto_fulfill_max_cost is null or (p.supplier_shipping is not null and p.supplier_price_ils + p.supplier_shipping <= p.auto_fulfill_max_cost))
  ) as ready_for_paid_order,
  array_remove(array[
    case when p.active is not true then 'product_inactive' end,
    case when lower(coalesce(p.supplier,'')) not in ('aliexpress','cj') then 'unsupported_supplier' end,
    case when nullif(trim(coalesce(p.supplier_product_id,'')),'') is null then 'supplier_product_id_missing' end,
    case when nullif(trim(coalesce(p.supplier_sku_id,'')),'') is null then 'supplier_sku_id_missing' end,
    case when (case when lower(coalesce(p.supplier,'')) = 'cj' then p.fulfillment_verified_at else p.sku_verified_at end) is null then 'supplier_sku_not_verified' end,
    case when p.supplier_in_stock is false then 'supplier_out_of_stock' end,
    case when p.supplier_in_stock is null then 'supplier_stock_unknown' end,
    case when p.supplier_shipping_available is false then 'supplier_shipping_unavailable' end,
    case when p.supplier_shipping_available is null then 'supplier_shipping_unknown' end,
    case when p.supplier_price_ils is null then 'supplier_price_unknown' end,
    case when p.last_sync_at is null or p.last_sync_at < now() - make_interval(mins => least(1440, greatest(15, coalesce(s.supplier_quote_ttl_minutes,480)))) then 'supplier_product_sync_stale' end,
    case when p.shipping_last_checked_at is null or p.shipping_last_checked_at < now() - make_interval(mins => least(1440, greatest(15, coalesce(s.supplier_quote_ttl_minutes,480)))) then 'supplier_shipping_sync_stale' end,
    case when p.supplier_sync_error is not null then 'supplier_sync_error' end,
    case when p.shipping_sync_error is not null then 'shipping_sync_error' end,
    case when p.supplier_price_ils is not null and p.selling_price - p.supplier_price_ils
      - ((p.selling_price + coalesce(p.supplier_shipping,0)) * coalesce(s.pricing_fee_percent,0) / 100)
      - coalesce(s.pricing_fee_fixed_ils,0) - coalesce(s.pricing_reserve_ils,0)
      < greatest(20, coalesce(p.minimum_profit, s.minimum_profit_ils, 20)) then 'minimum_profit_not_met' end,
    case when p.auto_fulfill_max_cost is not null and (p.supplier_price_ils is null or p.supplier_shipping is null) then 'supplier_cost_unknown_for_auto_limit' end,
    case when p.auto_fulfill_max_cost is not null and p.supplier_price_ils is not null and p.supplier_shipping is not null and p.supplier_price_ils + p.supplier_shipping > p.auto_fulfill_max_cost then 'supplier_cost_above_auto_limit' end
  ], null) as blockers
from public.products p
left join public.site_settings s on s.id = 'primary';

alter view public.product_fulfillment_readiness set (security_invoker = true);
revoke all on public.product_fulfillment_readiness from public, anon, authenticated;
grant select on public.product_fulfillment_readiness to service_role;

create or replace function public.get_launch_cron_status()
returns table(jobname text, schedule text, active boolean)
language sql stable security definer
set search_path = pg_catalog, public, cron
as $$
  select j.jobname::text, j.schedule::text, j.active
  from cron.job as j
  where j.jobname in ('aliexpress-catalog-hourly','supplier-optimizer-hourly','cj-sourcing-hourly','cj-catalog-hourly','cj-sourcing-daily-retry','cj-orders-every-30m')
  order by j.jobname;
$$;
revoke all on function public.get_launch_cron_status() from public, anon, authenticated;
grant execute on function public.get_launch_cron_status() to service_role;

do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'supplier-optimizer-hourly' limit 1;
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
end $$;

select cron.schedule(
  'supplier-optimizer-hourly',
  '25 * * * *',
  $job$
  select net.http_get(
    url := 'https://aluf-hakelim-v2-ready.vercel.app/api/supplier-optimizer-worker',
    params := '{}'::jsonb,
    headers := jsonb_build_object('Accept','application/json','x-cj-worker-token',(select decrypted_secret from vault.decrypted_secrets where name='cj_worker_token' limit 1)),
    timeout_milliseconds := 60000
  );
  $job$
);
