create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  status text not null default 'draft',
  currency text not null default 'ILS',
  total numeric(12,2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  customer jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- No public policies are created on purpose.
-- Orders are written only by the server using SUPABASE_SERVICE_ROLE_KEY.
