create table if not exists public.payment_refund_requests (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  order_id text not null references public.orders(order_id) on delete restrict,
  provider text not null default 'paypal' check (provider = 'paypal'),
  requested_amount numeric(12,2) not null check (requested_amount > 0 and requested_amount <= 1000000),
  currency text not null default 'ILS' check (currency = 'ILS'),
  status text not null default 'started' check (status in ('started','pending','completed','failed')),
  provider_refund_id text unique,
  provider_status text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_refund_requests_order_idx
on public.payment_refund_requests(order_id, created_at desc);

alter table public.payment_refund_requests enable row level security;
revoke all on table public.payment_refund_requests from anon, authenticated;
grant all on table public.payment_refund_requests to service_role;
