-- Supplier-order safety schema applied to production on 2026-08-16.

alter table public.orders
  add column if not exists supplier_order_ids jsonb not null default '[]'::jsonb;

alter table public.orders
  drop constraint if exists orders_supplier_order_ids_array;
alter table public.orders
  add constraint orders_supplier_order_ids_array
  check (jsonb_typeof(supplier_order_ids) = 'array' and jsonb_array_length(supplier_order_ids) <= 50);

create table if not exists public.supplier_order_attempts (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(order_id) on delete cascade,
  attempt_key uuid not null default gen_random_uuid(),
  request_fingerprint text not null,
  status text not null default 'prepared',
  supplier_order_ids jsonb not null default '[]'::jsonb,
  error_code text,
  error_message text,
  response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint supplier_order_attempts_status_check check (status in ('prepared','sending','created','payment_pending','paid','ambiguous','failed','cancelled','reconciled')),
  constraint supplier_order_attempts_ids_array check (jsonb_typeof(supplier_order_ids) = 'array' and jsonb_array_length(supplier_order_ids) <= 50),
  constraint supplier_order_attempts_fingerprint_check check (request_fingerprint ~ '^[a-f0-9]{64}$')
);

create unique index if not exists supplier_order_attempts_attempt_key_uidx
  on public.supplier_order_attempts(attempt_key);
create index if not exists supplier_order_attempts_order_idx
  on public.supplier_order_attempts(order_id, created_at desc);
create unique index if not exists supplier_order_attempts_open_order_uidx
  on public.supplier_order_attempts(order_id)
  where status in ('sending','created','payment_pending','paid','ambiguous');

alter table public.supplier_order_attempts enable row level security;
revoke all privileges on table public.supplier_order_attempts from public, anon, authenticated;
revoke all privileges on sequence public.supplier_order_attempts_id_seq from public, anon, authenticated;
grant all privileges on table public.supplier_order_attempts to service_role;
grant all privileges on sequence public.supplier_order_attempts_id_seq to service_role;

create or replace function public.touch_supplier_order_attempt_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke execute on function public.touch_supplier_order_attempt_updated_at() from public, anon, authenticated;

drop trigger if exists supplier_order_attempts_touch_updated_at on public.supplier_order_attempts;
create trigger supplier_order_attempts_touch_updated_at
before update on public.supplier_order_attempts
for each row execute function public.touch_supplier_order_attempt_updated_at();

alter table public.products drop constraint if exists products_max_order_quantity_check;
alter table public.products add constraint products_max_order_quantity_check check (max_order_quantity between 1 and 20);

alter table public.products drop constraint if exists products_supplier_product_id_format;
alter table public.products add constraint products_supplier_product_id_format
check (supplier_product_id is null or supplier_product_id ~ '^\d{8,20}$');

alter table public.products drop constraint if exists products_supplier_url_format;
alter table public.products add constraint products_supplier_url_format
check (supplier_url is null or supplier_url ~* '^https://([a-z0-9-]+\.)*aliexpress\.com/');

alter table public.products drop constraint if exists products_image_url_format;
alter table public.products add constraint products_image_url_format
check (image_url is null or image_url ~* '^(https://|/)');
